blank_issues_enabled: false
contact_links:
  - name: Ask questions
    url: https://stackoverflow.com/questions/tagged/pyrogram
    about: You can ask general Pyrogram questions at StackOverflow.
  - name: Join the Telegram Chat
    url: https://t.me/reyysupport
    about: Join the official Support Chat for rvpyro.